src/yano_marina/beans/Comment.java
package yano_marina.beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    private static final long serialVersionUID = 1L;

    private int no;
    private int user_id;
    private String name;
    private String text;
    private Date post_date;
    private int posts_no;
    private int deleted;
    private Date update_date;

	public int getNo() {
		return no;
	}
	public void setNo(int no) {
		this.no = no;
	}
	public int getUserId() {
		return user_id;
	}
	public void setUserId(int user_id) {
		this.user_id = user_id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getPost_date() {
		return post_date;
	}
	public void setPost_date(Date post_date) {
		this.post_date = post_date;
	}
	public int getPostsNo() {
		return posts_no;
	}
	public void setPostsNo(int posts_no) {
		this.posts_no = posts_no;
	}
	public int getDeleted() {
		return deleted;
	}
	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}
	public Date getUpdate_date() {
		return update_date;
	}
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}

}

src/yano_marina/beans/Post.java
package yano_marina.beans;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
    private static final long serialVersionUID = 1L;

    private int no;
    private int user_Id;
    private String name;
    private String subject;
    private String text;
    private String category;
    private Date post_date;
    private int deleted;
    private Date updated_date;

	public int getNo() {
		return no;
	}
	public void setNo(int no) {
		this.no = no;
	}
	public int getUserId() {
		return user_Id;
	}
	public void setUserId(int user_Id) {
		this.user_Id = user_Id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getPostDate() {
		return post_date;
	}
	public void setPostDate(Date post_date) {
		this.post_date = post_date;
	}
	public int getDeleted() {
		return deleted;
	}
	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}
	public Date getUpdatedDate() {
		return updated_date;
	}
	public void setUpdatedDate(Date updated_date) {
		this.updated_date = updated_date;
	}

}

src/yano_marina/beans/User.java
package yano_marina.beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;


    private int id;
    private String login_id;
    private String password;
    private String name;
    private int branch;
    private int department;
    private int stop_revival;
    private Date updated_date;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getLoginId() {
		return login_id;
	}
	public void setLoginId(String login_id) {
		this.login_id = login_id;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranch() {
		return branch;
	}
	public void setBranch(int branch) {
		this.branch = branch;
	}
	public int getDepartment() {
		return department;
	}
	public void setDepartment(int department) {
		this.department = department;
	}
	public int getStopRevival() {
		return stop_revival;
	}
	public void setStopRevival(int stop_revival) {
		this.stop_revival = stop_revival;
	}
	public Date getUpdatedDate() {
		return updated_date;
	}
	public void setUpdatedDate(Date updated_date) {
		this.updated_date = updated_date;
	}

}

src/yano_marina/controller/HomeServlet.java
package yano_marina.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import yano_marina.beans.PostComment;
import yano_marina.beans.User;
import yano_marina.beans.UserPost;
import yano_marina.service.CommentService;
import yano_marina.service.PostService;


@WebServlet(urlPatterns = {"/index.jsp"})
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

        User user = (User) request.getSession().getAttribute("loginUser");
        HttpSession session = request.getSession();
        List<String> messages = new ArrayList<String>();

        if(user == null) {
        	session.setAttribute("errorMessages", messages);
    		messages.add("ログインしてください");
        	request.getRequestDispatcher("login.jsp").forward(request, response);
        }

        if(user != null) {
        	List<UserPost> posts = new PostService().getPost((request.getParameter("categorysearch")),
        		(request.getParameter("startdate")), (request.getParameter("enddate")));

        	String categorysearch = request.getParameter("categorysearch");
        	String startdate = request.getParameter("startdate");
        	String enddate = request.getParameter("enddate");

        	if(StringUtils.isEmpty(categorysearch) == false) {
        		request.setAttribute("categorysearch", categorysearch);
        	}
        	if(StringUtils.isEmpty(startdate) == false) {
        		Date startDate = java.sql.Date.valueOf(startdate);
        		request.setAttribute("startdate", startDate);
        	}
        	if(StringUtils.isEmpty(enddate) == false) {
        		Date endDate = java.sql.Date.valueOf(enddate);
        		request.setAttribute("enddate", endDate);
        	}

        	request.setAttribute("posts", posts);

        	List<PostComment> comments = new CommentService().getComment();

        	request.setAttribute("comments", comments);

        	request.getRequestDispatcher("/home.jsp").forward(request, response);
        }
	}


}

src/yano_marina/controller/LoginServlet.java
package yano_marina.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import yano_marina.beans.User;
import yano_marina.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

    	request.getRequestDispatcher("login.jsp").forward(request, response);

    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	String loginId = request.getParameter("login_id");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        User user = loginService.login(loginId, password);
        HttpSession session = request.getSession();

        if (user != null) {
        	int stopRevival = user.getStopRevival();
        	if(stopRevival == 0) {
        		session.setAttribute("loginUser", user);
        		response.sendRedirect("./");
        	}else {
                List<String> messages = new ArrayList<String>();
                messages.add("ログインIDまたはパスワードが誤っています");

                session.setAttribute("errorMessages", messages);
                request.setAttribute("errorLoginId", loginId);

                request.getRequestDispatcher("login.jsp").forward(request, response);
        	}
        } else {
            List<String> messages = new ArrayList<String>();

            if(StringUtils.isEmpty(loginId) == true || StringUtils.isEmpty(password) == true) {
            	messages.add("ログインIDまたはパスワードが入力されていません");
            }else {
            	messages.add("ログインIDまたはパスワードが誤っています");
            }

            session.setAttribute("errorMessages", messages);
            request.setAttribute("errorLoginId", loginId);

            request.getRequestDispatcher("login.jsp").forward(request, response);
        }
    }
}

src/yano_marina/controller/ManagementServlet.java
package yano_marina.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import yano_marina.beans.BranchDepartmentUser;
import yano_marina.beans.User;
import yano_marina.service.UserService;


@WebServlet(urlPatterns = {"/management"})
public class ManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		User user = (User) request.getSession().getAttribute("loginUser");
    	List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();

    	if(user == null) {
    		session.setAttribute("errorMessages", messages);
    		messages.add("ログインしてください");
    		response.sendRedirect("./");
    	}else if(user != null){
    		int department = user.getDepartment();
    		if(department != 1) {
    			session.setAttribute("errorMessages", messages);
        		messages.add("権限がありません");
        		response.sendRedirect("./");
    		}else if(department == 1){
    			List<BranchDepartmentUser> users = new UserService().getUsers();
    			request.setAttribute("users", users);
    			request.getRequestDispatcher("/management.jsp").forward(request, response);
    		}
    	}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		if(request.getParameter("stop") != null) {
			new UserService().stop(
					(Integer.parseInt(request.getParameter("stop"))),
					(Integer.parseInt(request.getParameter("id"))));
			response.sendRedirect("management");
		}
		if(request.getParameter("revival") != null) {
			new UserService().stop(
					(Integer.parseInt(request.getParameter("revival"))),
					(Integer.parseInt(request.getParameter("id"))));
			response.sendRedirect("management");
		}

	}



}

src/yano_marina/controller/NewPostServlet.java
package yano_marina.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import yano_marina.beans.Post;
import yano_marina.beans.User;
import yano_marina.service.PostService;


@WebServlet(urlPatterns = {"/newPost"})
public class NewPostServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		User user = (User) request.getSession().getAttribute("loginUser");
    	List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();

		if(user == null) {
			session.setAttribute("errorMessages", messages);
			messages.add("ログインしてください");
			response.sendRedirect("./");
    	}else if(user != null){
    		request.getRequestDispatcher("newpost.jsp").forward(request, response);
    	}
	}


	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();

		List<String> messages = new ArrayList<String>();

		if(isValid(request, messages) == true) {

			User user = (User) session.getAttribute("loginUser");

			Post post = new Post();
			post.setSubject(request.getParameter("subject"));
			post.setText(request.getParameter("text"));
			post.setCategory(request.getParameter("category"));
			post.setDeleted(Integer.parseInt(request.getParameter("postDeleted")));
			post.setUserId(user.getId());

			new PostService().register(post);

			response.sendRedirect("./");
		}else {
			String subject = request.getParameter("subject");
			String text =request.getParameter("text");
			String category = request.getParameter("category");

			session.setAttribute("errorMessages", messages);
			request.setAttribute("errorSubject", subject);
			request.setAttribute("errorText", text);
			request.setAttribute("errorCategory", category);
			request.getRequestDispatcher("newpost.jsp").forward(request, response);
		}
	}


	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String subject = request.getParameter("subject");
		String text = request.getParameter("text");
		String category = request.getParameter("category");

		if (StringUtils.isEmpty(subject) == true) {
			messages.add("件名を入力してください");
		}else if (30 < subject.length()) {
			messages.add("件名は30字以下で入力してください");
		}
		if (StringUtils.isEmpty(text) == true) {
			messages.add("本文を入力してください");
		}else if (1000 < text.length()) {
			messages.add("本文は1000文字以内で入力してください");
		}
		if (StringUtils.isEmpty(category) == true) {
			messages.add("カテゴリを入力してください");
		}else if (10 < category.length()) {
			messages.add("カテゴリは10文字以下で入力してください");
		}

		if(messages.size() == 0) {
			return true;
		}else {
			return false;
		}

	}

}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>掲示板システム</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

			<div class="header">
				<c:if test="${ empty loginUser }">
					<a href="login">ログイン</a>
				</c:if>
				<c:if test="${ not empty loginUser }">
					<a href="newPost">新規投稿</a><br>
					<a href="management">ユーザー管理画面</a><br>
					<form action="./" method="get">
						カテゴリー検索：<input type="text" size="15" name="categorysearch" value="${categorysearch}">
						<input type="submit" value="検索" id="search"><br>
						投稿日時検索 ：<input type="date" size="15" name="startdate" value="${startdate}">～
						<input type="date" size="15" name="enddate" value="${enddate}">
						<input type="submit" value="検索" id="search"><br>
					</form>
					<a href="logout">ログアウト</a>
				</c:if>
			</div>
			<c:if test="${ not empty loginUser }">
				<div class="profile">
					<div class="name"><h2><c:out value="${loginUser.name}" />のページ</h2></div>
				</div>
			</c:if>
			<c:if test="${ not empty loginUser }">
				<div class="posts">
					<div><h3>投稿一覧</h3></div>
					<c:forEach items="${posts}" var="post">
					<c:if test="${ post.deleted == 0}">
						<p>------------------------------------------------------</p>
						<div class="subject"><p>【件名】<c:out value="${post.subject}" /></div>
						<div class="text"><c:out value="${post.text}" /></div>
						<div class="category"><p>【カテゴリー】<c:out value="${post.category}" /></div>
						<div class="date"><p>【投稿日時】<fmt:formatDate value="${post.post_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
						<div class="name"><p>【投稿者】<c:out value="${post.name}" /></div>
						<c:if test="${post.userId == loginUser.id}">
							<form method="post" action="deletePost">
								<input name="no" type="hidden" value="${post.no}">
								<input name="postDelete" type="hidden" value="1">
								<input type="submit" value="投稿削除" id="post_delete_button">
							</form>
						</c:if>
						<p>
						<form action="newComment" method="post">
							コメントする<br />
							<textarea name="comment" cols="50" rows="2" class="comment-box"></textarea>
							<br />
							<input name="postNo" type="hidden" value="${post.no}">
							<input name="commentDeleted" type="hidden" value="0" id="commentDeleted">
							<input type="submit" value="送信する" id="new_comment_button">
						</form>
						<c:forEach items="${comments}" var="comment">
							<div class="comment">
							<c:if test="${comment.postsNo == post.no}">
								<c:if test="${comment.deleted == 0}">
									<p>【コメント】</p>
									<div class="commentname"><c:out value="${comment.name}"/>　さんより</div>
									<div class="comment"><p><c:out value="${comment.text}"/></div>
									<c:if test="${comment.userId == loginUser.id}">
										<form method="post" action="deleteComment">
											<input name="no" type="hidden" value="${comment.no}">
											<input name="commentDelete" type="hidden" value="1">
											<input type="submit" value="コメント削除" id="comment_delete_button">
										</form>
									</c:if>
								</c:if>
							</c:if>
							</div>
						</c:forEach>
					</c:if>
					</c:forEach>
				</div>
			</c:if>
			<div class="copylight"> Copyright(c)YanoMarina</div>
		</div>

</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">

			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>

			<form action="login" method="post"><br />

				<label for="loginId">ログインID</label>
				<input name="login_id" value="${errorLoginId}" id="login_id"/> <br />
				<p>
				<label for="password">パスワード</label>
				<input name="password" type="password" id="loginPassword"/> <br />
				<p>
				<input type="submit" value="ログイン" id="login_button"/>
				<br />

			</form>
			<div class="copylight"> Copyright(c)YanoMarina</div>
		</div>
	</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>ユーザー管理</title>
	<link href="./css/style.css" rel="stylesheet" type="text/css">

	</head>
	<body>
		<div class="main-contents">
			<div class="header">
					<a href="./">ホームに戻る</a><br>
					<a href="signup">新規登録</a>
			</div>
			<div class="management-table">
				<table border="1">
					<tr>
						<th>編集</th>
						<th>停止・復活</th>
						<th>ログインID</th>
						<th>ユーザー名</th>
						<th>支店</th>
						<th>部署・役職</th>
					</tr>
					<c:forEach items="${users}" var="users">
					<tr>
						<td>
						<form method="post" action="edit">
							<button name="edit" type="submit" value="${users.id}" id="edit_button">編集</button>
						</form>
						</td>
						<td>
						<form method="post" action="management">
							<c:if test="${users.stopRevival == 0}">
								<input name="id" type="hidden" value="${users.id}" />
								<input name="stop" type="hidden" value="1">
								<input type="submit" value="停止" onClick="return confirm('アカウントを停止します')" id="stop_button">
							</c:if>
							<c:if test="${users.stopRevival == 1}">
								<input name="id" type="hidden" value="${users.id}" />
								<input name="revival" type="hidden" value="0">
								<input type="submit" value="復活" onClick="return confirm('アカウントを復活します')" id="revival_button">
							</c:if>
						</form>
						</td>
						<td><c:out value="${users.loginId}"/></td>
						<td><c:out value="${users.name}"/></td>
						<td><c:out value="${users.branchName}"/></td>
						<td><c:out value="${users.departmentName}"/></td>
					</tr>
					</c:forEach>
				</table>
			</div>
		</div>
		<div class="copylight"> Copyright(c)YanoMarina</div>

	</body>
</html>

WebContent/newpost.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>新規投稿</title>
	<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
		 <c:if test="${ not empty errorMessages }">
		 	<div class="errorMessages">
		 		<ul>
		 			<c:forEach items="${errorMessages}" var="message">
		 				<li><c:out value="${message}" />
		 			</c:forEach>
		 		</ul>
		 	</div>
		 	<c:remove var="errorMessages" scope="session" />
		 </c:if>

		</div>
		<div class="header">
			<c:if test="${ not empty loginUser }">
				<a href="./">ホームに戻る</a>
				<div class="form-area">
					<p>新規投稿</p>
					<form action="newPost" method="post">
					件名<br/>
					<input type="text" value="${errorSubject}" name="subject"><br/>
					本文<br/>
					<textarea name="text" rows="30" cols="70" class="text">${errorText}</textarea><br/>
					カテゴリー<br/>
					<input type="text" value="${errorCategory}" name="category"><br/>
					<input type="hidden" value="0" name="postDeleted" id="postDeleted">
					<p>
					<input type="submit" value="投稿" id="post_button"><br/>
					</form>
				</div>
				<div class="copylight"> Copyright(c)YanoMarina</div>
			</c:if>
		</div>
	</body>
</html>

WebContent/settings.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${editUser.name}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <form action="settings" method="post"><br />
            	<br />
            	<input name="id" value="${editUser.id}" id="id" type="hidden" />
                <label for="name">ユーザー名</label>
                <input name="name" value="${editUser.name}" id="name" /><br />
				<p>
                <label for="loginId">ログインID</label>
                <input name="loginId" value="${editUser.loginId}" id="loginId" /> <br />
				<p>
                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />
				<p>
                <label for="passwordCheck">パスワード確認</label>
                <input name="passwordCheck" type="password" id="passwordCheck" /> <br />
				<p>
                <label for="branch">支店</label>
                <select name="branch" id="branch" >
                <option value="1" <c:if test="${editUser.branch == 1}">selected</c:if>>本社</option>
                <option value="2" <c:if test="${editUser.branch == 2}">selected</c:if>>支店Ａ</option>
                <option value="3" <c:if test="${editUser.branch == 3}">selected</c:if>>支店Ｂ</option>
                <option value="4" <c:if test="${editUser.branch == 4}">selected</c:if>>支店Ｃ</option>
                </select>
				<p>
                <label for="department">部署・役職番号</label>
                <select name="department" id="department">
                <option value="1" <c:if test="${editUser.department == 1}">selected</c:if>>人事総務部</option>
                <option value="2" <c:if test="${editUser.department == 2}">selected</c:if>>情報管理担当者</option>
                <option value="3" <c:if test="${editUser.department == 3}">selected</c:if>>支店長</option>
                <option value="4" <c:if test="${editUser.department == 4}">selected</c:if>>社員</option>
                </select>
                <br/>

                <input name="stopRevival" value="${editUser.stopRevival}" id="stopRevival" type="hidden" />
				<p>
                <input type="submit" value="変更" id="change_button"/> <br />
                <p>
                <a href="management">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)MarinaYano</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>ユーザー新規登録</title>
	<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <form action="signup" method="post">
                <br />
                <label for="name">ユーザー名</label>
                <input name="name" value="${errorName}" id="name" /><br />

                <label for="loginId">ログインID</label>
                <input name="loginId" value="${errorLoginId}" id="loginId" /> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />

                <label for="passwordCheck">パスワード確認</label>
                <input name="passwordCheck" type="password" id="passwordCheck" /> <br />

                <label for="branch">支店</label>
                <select name="branch" id="branch" >
                <option value="1" <c:if test="${errorBranch == 1}">selected</c:if>>本社</option>
                <option value="2" <c:if test="${errorBranch == 2}">selected</c:if>>支店Ａ</option>
                <option value="3" <c:if test="${errorBranch == 3}">selected</c:if>>支店Ｂ</option>
                <option value="4" <c:if test="${errorBranch == 4}">selected</c:if>>支店Ｃ</option>
                </select>
                <br/>

                <label for="department">部署・役職</label>
                <select name="department" id="department" >
                <option value="1" <c:if test="${errorDepartment == 1}">selected</c:if>>人事総務部</option>
                <option value="2" <c:if test="${errorDepartment == 2}">selected</c:if>>情報管理担当者</option>
                <option value="3" <c:if test="${errorDepartment == 3}">selected</c:if>>支店長</option>
                <option value="4" <c:if test="${errorDepartment == 4}">selected</c:if>>社員</option>
                </select>
                <br />

                <input name="stopRevival" value="0" id="stopRevival" type="hidden">

                <br /> <input type="submit" value="新規登録" /> <br />

                <a href="management">戻る</a>
            </form>

            <div class="copyright">Copyright(c)Yano</div>
        </div>

	</body>
</html>